// Spoils of the Hunt: trophy fusion recipes. Generated by generate-sources.ps1 - do not edit by hand.
// Teaches the alchemy manager only the fusion recipes whose two trophies are in Geralt's bags, so the
// panel stays short. The recipes themselves live in the DLC XML; nothing is written to the save.
@wrapMethod(W3AlchemyManager)
function Init(optional alchemyRecipes : array<name>)
{
	var itemA, itemB, recipe, owned : array<name>;
	var i : int;

	wrappedMethod(alchemyRecipes);
	SOTH_FusionTable1(itemA, itemB, recipe);
	SOTH_FusionTable2(itemA, itemB, recipe);
	SOTH_FusionTable3(itemA, itemB, recipe);
	SOTH_FusionTable4(itemA, itemB, recipe);
	SOTH_FusionTable5(itemA, itemB, recipe);
	SOTH_FusionTable6(itemA, itemB, recipe);
	SOTH_FusionTable7(itemA, itemB, recipe);
	SOTH_FusionTable8(itemA, itemB, recipe);
	SOTH_FusionTable9(itemA, itemB, recipe);
	SOTH_FusionTable10(itemA, itemB, recipe);
	for(i=0; i<recipe.Size(); i+=1)
	{
		if(thePlayer.inv.GetItemQuantityByName(itemA[i]) > 0 && thePlayer.inv.GetItemQuantityByName(itemB[i]) > 0)
			owned.PushBack(recipe[i]);
	}
	if(owned.Size() > 0)
		LoadRecipesCustomXMLData(owned);
}

function SOTH_FusionTable1(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('sq108_griffin_trophy'); recipe.PushBack('soth_fuse_q002_griffin__sq108_griffin__1');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('sq108_griffin_trophy'); recipe.PushBack('soth_fuse_q002_griffin__sq108_griffin__2');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mq7009_griffin_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mq7009_griffin__1');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mq7009_griffin_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mq7009_griffin__2');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh301_gryphon__1');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh301_gryphon__2');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh301_gryphon__3');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh301_gryphon__4');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh210_lamia__1');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh210_lamia__2');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh210_lamia__3');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh210_lamia__4');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh303_succubus__1');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh303_succubus__2');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh303_succubus__3');
	itemA.PushBack('q002_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_q002_griffin__mh303_succubus__4');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mq7009_griffin_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mq7009_griffin__1');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mq7009_griffin_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mq7009_griffin__2');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh301_gryphon__1');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh301_gryphon__2');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh301_gryphon__3');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh301_gryphon__4');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh210_lamia__1');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh210_lamia__2');
}

function SOTH_FusionTable2(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh210_lamia__3');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh210_lamia__4');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh303_succubus__1');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh303_succubus__2');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh303_succubus__3');
	itemA.PushBack('sq108_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_sq108_griffin__mh303_succubus__4');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh301_gryphon__1');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh301_gryphon__2');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh301_gryphon__3');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh301_gryphon_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh301_gryphon__4');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh210_lamia__1');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh210_lamia__2');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh210_lamia__3');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh210_lamia__4');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh303_succubus__1');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh303_succubus__2');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh303_succubus__3');
	itemA.PushBack('mq7009_griffin_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mq7009_griffin__mh303_succubus__4');
	itemA.PushBack('mh301_gryphon_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_mh301_gryphon__mh210_lamia__1');
	itemA.PushBack('mh301_gryphon_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_mh301_gryphon__mh210_lamia__2');
	itemA.PushBack('mh301_gryphon_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_mh301_gryphon__mh210_lamia__3');
	itemA.PushBack('mh301_gryphon_trophy'); itemB.PushBack('mh210_lamia_trophy'); recipe.PushBack('soth_fuse_mh301_gryphon__mh210_lamia__4');
	itemA.PushBack('mh301_gryphon_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mh301_gryphon__mh303_succubus__1');
	itemA.PushBack('mh301_gryphon_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mh301_gryphon__mh303_succubus__2');
}

function SOTH_FusionTable3(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('mh301_gryphon_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mh301_gryphon__mh303_succubus__3');
	itemA.PushBack('mh210_lamia_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mh210_lamia__mh303_succubus__1');
	itemA.PushBack('mh210_lamia_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mh210_lamia__mh303_succubus__2');
	itemA.PushBack('mh210_lamia_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mh210_lamia__mh303_succubus__3');
	itemA.PushBack('mh210_lamia_trophy'); itemB.PushBack('mh303_succubus_trophy'); recipe.PushBack('soth_fuse_mh210_lamia__mh303_succubus__4');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mh105_wyvern_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mh105_wyvern__1');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mh105_wyvern_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mh105_wyvern__2');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mh105_wyvern_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mh105_wyvern__3');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mh105_wyvern_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mh105_wyvern__4');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq1051_wyvern_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq1051_wyvern__1');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq1051_wyvern_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq1051_wyvern__2');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq1051_wyvern_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq1051_wyvern__3');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq1051_wyvern_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq1051_wyvern__4');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mh208_forktail__1');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mh208_forktail__2');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mh208_forktail__3');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq7018_basilisk__1');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq7018_basilisk__2');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq7018_basilisk__3');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq7010_dracolizard__1');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq7010_dracolizard__2');
	itemA.PushBack('mh101_cockatrice_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mh101_cockatrice__mq7010_dracolizard__3');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mq1051_wyvern_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mq1051_wyvern__1');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mq1051_wyvern_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mq1051_wyvern__2');
}

function SOTH_FusionTable4(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mh208_forktail__1');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mh208_forktail__2');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mh208_forktail__3');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mh208_forktail__4');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mq7018_basilisk__1');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mq7018_basilisk__2');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mq7018_basilisk__3');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mq7018_basilisk__4');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mq7010_dracolizard__1');
	itemA.PushBack('mh105_wyvern_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mh105_wyvern__mq7010_dracolizard__2');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mh208_forktail__1');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mh208_forktail__2');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mh208_forktail__3');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mh208_forktail_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mh208_forktail__4');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mq7018_basilisk__1');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mq7018_basilisk__2');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mq7018_basilisk__3');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mq7018_basilisk__4');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mq7010_dracolizard__1');
	itemA.PushBack('mq1051_wyvern_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mq1051_wyvern__mq7010_dracolizard__2');
	itemA.PushBack('mh208_forktail_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh208_forktail__mq7018_basilisk__1');
	itemA.PushBack('mh208_forktail_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh208_forktail__mq7018_basilisk__2');
	itemA.PushBack('mh208_forktail_trophy'); itemB.PushBack('mq7018_basilisk_trophy'); recipe.PushBack('soth_fuse_mh208_forktail__mq7018_basilisk__3');
	itemA.PushBack('mh208_forktail_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mh208_forktail__mq7010_dracolizard__1');
}

function SOTH_FusionTable5(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('mh208_forktail_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mh208_forktail__mq7010_dracolizard__2');
	itemA.PushBack('mh208_forktail_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mh208_forktail__mq7010_dracolizard__3');
	itemA.PushBack('mq7018_basilisk_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mq7018_basilisk__mq7010_dracolizard__1');
	itemA.PushBack('mq7018_basilisk_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mq7018_basilisk__mq7010_dracolizard__2');
	itemA.PushBack('mq7018_basilisk_trophy'); itemB.PushBack('mq7010_dracolizard_trophy'); recipe.PushBack('soth_fuse_mq7018_basilisk__mq7010_dracolizard__3');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh302_leshy_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh302_leshy__1');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh302_leshy_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh302_leshy__2');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh302_leshy_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh302_leshy__3');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh206_fiend_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh206_fiend__1');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh206_fiend_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh206_fiend__2');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh206_fiend_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh206_fiend__3');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh206_fiend_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh206_fiend__4');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh107_czart__1');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh107_czart__2');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh107_czart__3');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mq7002_spriggan__1');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mq7002_spriggan__2');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh305_doppler__1');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh305_doppler__2');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh305_doppler__3');
	itemA.PushBack('mh204_leshy_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh204_leshy__mh305_doppler__4');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh206_fiend_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh206_fiend__1');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh206_fiend_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh206_fiend__2');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh206_fiend_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh206_fiend__3');
}

function SOTH_FusionTable6(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh206_fiend_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh206_fiend__4');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh107_czart__1');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh107_czart__2');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh107_czart__3');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mq7002_spriggan__1');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mq7002_spriggan__2');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh305_doppler__1');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh305_doppler__2');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh305_doppler__3');
	itemA.PushBack('mh302_leshy_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh302_leshy__mh305_doppler__4');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mh107_czart__1');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mh107_czart__2');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mh107_czart__3');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mh107_czart_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mh107_czart__4');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mq7002_spriggan__1');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mq7002_spriggan__2');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mq7002_spriggan__3');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mh305_doppler__1');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mh305_doppler__2');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mh305_doppler__3');
	itemA.PushBack('mh206_fiend_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh206_fiend__mh305_doppler__4');
	itemA.PushBack('mh107_czart_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh107_czart__mq7002_spriggan__1');
	itemA.PushBack('mh107_czart_trophy'); itemB.PushBack('mq7002_spriggan_trophy'); recipe.PushBack('soth_fuse_mh107_czart__mq7002_spriggan__2');
	itemA.PushBack('mh107_czart_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh107_czart__mh305_doppler__1');
}

function SOTH_FusionTable7(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('mh107_czart_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh107_czart__mh305_doppler__2');
	itemA.PushBack('mh107_czart_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh107_czart__mh305_doppler__3');
	itemA.PushBack('mh107_czart_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mh107_czart__mh305_doppler__4');
	itemA.PushBack('mq7002_spriggan_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mq7002_spriggan__mh305_doppler__1');
	itemA.PushBack('mq7002_spriggan_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mq7002_spriggan__mh305_doppler__2');
	itemA.PushBack('mq7002_spriggan_trophy'); itemB.PushBack('mh305_doppler_trophy'); recipe.PushBack('soth_fuse_mq7002_spriggan__mh305_doppler__3');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mh103_nightwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mh103_nightwraith__1');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mh103_nightwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mh103_nightwraith__2');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mh103_nightwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mh103_nightwraith__3');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mh308_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mh308_noonwraith__1');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mh308_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mh308_noonwraith__2');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mh308_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mh308_noonwraith__3');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mq0003_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mq0003_noonwraith__1');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mq0003_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mq0003_noonwraith__2');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mq0003_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mq0003_noonwraith__3');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mq7017_zmora_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mq7017_zmora__1');
	itemA.PushBack('mh207_wraith_trophy'); itemB.PushBack('mq7017_zmora_trophy'); recipe.PushBack('soth_fuse_mh207_wraith__mq7017_zmora__2');
	itemA.PushBack('mh103_nightwraith_trophy'); itemB.PushBack('mh308_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh103_nightwraith__mh308_noonwraith__1');
	itemA.PushBack('mh103_nightwraith_trophy'); itemB.PushBack('mh308_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh103_nightwraith__mh308_noonwraith__2');
	itemA.PushBack('mh103_nightwraith_trophy'); itemB.PushBack('mh308_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh103_nightwraith__mh308_noonwraith__3');
	itemA.PushBack('mh103_nightwraith_trophy'); itemB.PushBack('mq0003_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh103_nightwraith__mq0003_noonwraith__1');
	itemA.PushBack('mh103_nightwraith_trophy'); itemB.PushBack('mq0003_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh103_nightwraith__mq0003_noonwraith__2');
	itemA.PushBack('mh103_nightwraith_trophy'); itemB.PushBack('mq0003_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh103_nightwraith__mq0003_noonwraith__3');
	itemA.PushBack('mh103_nightwraith_trophy'); itemB.PushBack('mq7017_zmora_trophy'); recipe.PushBack('soth_fuse_mh103_nightwraith__mq7017_zmora__1');
}

function SOTH_FusionTable8(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('mh103_nightwraith_trophy'); itemB.PushBack('mq7017_zmora_trophy'); recipe.PushBack('soth_fuse_mh103_nightwraith__mq7017_zmora__2');
	itemA.PushBack('mh308_noonwraith_trophy'); itemB.PushBack('mq0003_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh308_noonwraith__mq0003_noonwraith__1');
	itemA.PushBack('mh308_noonwraith_trophy'); itemB.PushBack('mq0003_noonwraith_trophy'); recipe.PushBack('soth_fuse_mh308_noonwraith__mq0003_noonwraith__2');
	itemA.PushBack('mh308_noonwraith_trophy'); itemB.PushBack('mq7017_zmora_trophy'); recipe.PushBack('soth_fuse_mh308_noonwraith__mq7017_zmora__1');
	itemA.PushBack('mh308_noonwraith_trophy'); itemB.PushBack('mq7017_zmora_trophy'); recipe.PushBack('soth_fuse_mh308_noonwraith__mq7017_zmora__2');
	itemA.PushBack('mq0003_noonwraith_trophy'); itemB.PushBack('mq7017_zmora_trophy'); recipe.PushBack('soth_fuse_mq0003_noonwraith__mq7017_zmora__1');
	itemA.PushBack('mq0003_noonwraith_trophy'); itemB.PushBack('mq7017_zmora_trophy'); recipe.PushBack('soth_fuse_mq0003_noonwraith__mq7017_zmora__2');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('mh304_katakan_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__mh304_katakan__1');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('mh304_katakan_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__mh304_katakan__2');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('mh304_katakan_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__mh304_katakan__3');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('mh304_katakan_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__mh304_katakan__4');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('q704_garkain_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__q704_garkain__1');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('q704_garkain_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__q704_garkain__2');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('q704_garkain_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__q704_garkain__3');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('camm_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__camm__1');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('camm_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__camm__2');
	itemA.PushBack('mh104_ekimma_trophy'); itemB.PushBack('camm_trophy'); recipe.PushBack('soth_fuse_mh104_ekimma__camm__3');
	itemA.PushBack('mh304_katakan_trophy'); itemB.PushBack('q704_garkain_trophy'); recipe.PushBack('soth_fuse_mh304_katakan__q704_garkain__1');
	itemA.PushBack('mh304_katakan_trophy'); itemB.PushBack('q704_garkain_trophy'); recipe.PushBack('soth_fuse_mh304_katakan__q704_garkain__2');
	itemA.PushBack('mh304_katakan_trophy'); itemB.PushBack('camm_trophy'); recipe.PushBack('soth_fuse_mh304_katakan__camm__1');
	itemA.PushBack('mh304_katakan_trophy'); itemB.PushBack('camm_trophy'); recipe.PushBack('soth_fuse_mh304_katakan__camm__2');
	itemA.PushBack('q704_garkain_trophy'); itemB.PushBack('camm_trophy'); recipe.PushBack('soth_fuse_q704_garkain__camm__1');
	itemA.PushBack('mh106_gravehag_trophy'); itemB.PushBack('mh108_fogling_trophy'); recipe.PushBack('soth_fuse_mh106_gravehag__mh108_fogling__1');
	itemA.PushBack('mh106_gravehag_trophy'); itemB.PushBack('mh108_fogling_trophy'); recipe.PushBack('soth_fuse_mh106_gravehag__mh108_fogling__2');
}

function SOTH_FusionTable9(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('mh106_gravehag_trophy'); itemB.PushBack('mh108_fogling_trophy'); recipe.PushBack('soth_fuse_mh106_gravehag__mh108_fogling__3');
	itemA.PushBack('mh106_gravehag_trophy'); itemB.PushBack('mh108_fogling_trophy'); recipe.PushBack('soth_fuse_mh106_gravehag__mh108_fogling__4');
	itemA.PushBack('mh106_gravehag_trophy'); itemB.PushBack('mh203_water_hag_trophy'); recipe.PushBack('soth_fuse_mh106_gravehag__mh203_water_hag__1');
	itemA.PushBack('mh106_gravehag_trophy'); itemB.PushBack('mh203_water_hag_trophy'); recipe.PushBack('soth_fuse_mh106_gravehag__mh203_water_hag__2');
	itemA.PushBack('mh106_gravehag_trophy'); itemB.PushBack('mh203_water_hag_trophy'); recipe.PushBack('soth_fuse_mh106_gravehag__mh203_water_hag__3');
	itemA.PushBack('mh106_gravehag_trophy'); itemB.PushBack('mh203_water_hag_trophy'); recipe.PushBack('soth_fuse_mh106_gravehag__mh203_water_hag__4');
	itemA.PushBack('mh108_fogling_trophy'); itemB.PushBack('mh203_water_hag_trophy'); recipe.PushBack('soth_fuse_mh108_fogling__mh203_water_hag__1');
	itemA.PushBack('mh108_fogling_trophy'); itemB.PushBack('mh203_water_hag_trophy'); recipe.PushBack('soth_fuse_mh108_fogling__mh203_water_hag__2');
	itemA.PushBack('mh108_fogling_trophy'); itemB.PushBack('mh203_water_hag_trophy'); recipe.PushBack('soth_fuse_mh108_fogling__mh203_water_hag__3');
	itemA.PushBack('mh108_fogling_trophy'); itemB.PushBack('mh203_water_hag_trophy'); recipe.PushBack('soth_fuse_mh108_fogling__mh203_water_hag__4');
	itemA.PushBack('mh201_cave_troll_trophy'); itemB.PushBack('mh202_nekker_warrior_trophy'); recipe.PushBack('soth_fuse_mh201_cave_troll__mh202_nekker_warrior__1');
	itemA.PushBack('mh201_cave_troll_trophy'); itemB.PushBack('mh202_nekker_warrior_trophy'); recipe.PushBack('soth_fuse_mh201_cave_troll__mh202_nekker_warrior__2');
	itemA.PushBack('mh201_cave_troll_trophy'); itemB.PushBack('mh202_nekker_warrior_trophy'); recipe.PushBack('soth_fuse_mh201_cave_troll__mh202_nekker_warrior__3');
	itemA.PushBack('mh201_cave_troll_trophy'); itemB.PushBack('mh202_nekker_warrior_trophy'); recipe.PushBack('soth_fuse_mh201_cave_troll__mh202_nekker_warrior__4');
	itemA.PushBack('mh201_cave_troll_trophy'); itemB.PushBack('q701_cyclops_trophy'); recipe.PushBack('soth_fuse_mh201_cave_troll__q701_cyclops__1');
	itemA.PushBack('mh201_cave_troll_trophy'); itemB.PushBack('q701_cyclops_trophy'); recipe.PushBack('soth_fuse_mh201_cave_troll__q701_cyclops__2');
	itemA.PushBack('mh202_nekker_warrior_trophy'); itemB.PushBack('q701_cyclops_trophy'); recipe.PushBack('soth_fuse_mh202_nekker_warrior__q701_cyclops__1');
	itemA.PushBack('mh202_nekker_warrior_trophy'); itemB.PushBack('q701_cyclops_trophy'); recipe.PushBack('soth_fuse_mh202_nekker_warrior__q701_cyclops__2');
	itemA.PushBack('mh202_nekker_warrior_trophy'); itemB.PushBack('q701_cyclops_trophy'); recipe.PushBack('soth_fuse_mh202_nekker_warrior__q701_cyclops__3');
	itemA.PushBack('mh102_arachas_trophy'); itemB.PushBack('q603_sharley_trophy'); recipe.PushBack('soth_fuse_mh102_arachas__q603_sharley__1');
	itemA.PushBack('mh102_arachas_trophy'); itemB.PushBack('q603_sharley_trophy'); recipe.PushBack('soth_fuse_mh102_arachas__q603_sharley__2');
	itemA.PushBack('mh102_arachas_trophy'); itemB.PushBack('mh701_sharley_matriarch_trophy'); recipe.PushBack('soth_fuse_mh102_arachas__mh701_sharley_matriarch__1');
	itemA.PushBack('mh102_arachas_trophy'); itemB.PushBack('mh701_sharley_matriarch_trophy'); recipe.PushBack('soth_fuse_mh102_arachas__mh701_sharley_matriarch__2');
	itemA.PushBack('q603_sharley_trophy'); itemB.PushBack('mh701_sharley_matriarch_trophy'); recipe.PushBack('soth_fuse_q603_sharley__mh701_sharley_matriarch__1');
}

function SOTH_FusionTable10(out itemA : array<name>, out itemB : array<name>, out recipe : array<name>)
{
	itemA.PushBack('mh306_dao_trophy'); itemB.PushBack('mh307_minion_trophy'); recipe.PushBack('soth_fuse_mh306_dao__mh307_minion__1');
	itemA.PushBack('mh306_dao_trophy'); itemB.PushBack('mh307_minion_trophy'); recipe.PushBack('soth_fuse_mh306_dao__mh307_minion__2');
}
